It is variable but we will assign data at the later stage,the below two examples will give right picture

In [1]:
import tensorflow as tf
x=tf.placeholder("float",shape=None)##we dont know how many rows or columns are taking
y=x+2

with tf.Session() as sess:
    result=sess.run(y,feed_dict={x:[1,2,3]})
    print(result)

[ 3.  4.  5.]


In [2]:
import tensorflow as tf
x=tf.placeholder("float",shape=[None,3])##we dont row numbers and 3 columns should be taken
y=x+2

with tf.Session() as sess:
    result=sess.run(y,feed_dict={x:[[1,2,3],[4,5,6]]})
    print(result)

[[ 3.  4.  5.]
 [ 6.  7.  8.]]
